### ISSUE TITLE
Who made this repo and what was its intent?

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/full-stack-project-modeling-lab#1]
@ga-wdi-boston/core

**Comment by gaand** [comment]
Descoping is the first step to meeting expectations on the full stack projet.
Sequencing scope is the second step.
These are hard problems.

**Comment by payne-chris-r** [comment]
I think this is ok to close, yes? @ga-wdi-boston/core

**Comment by gaand** [comment]
@BenGitsCode Because I can't tell the intent here from the issue title or who you `@`ed, I'm closing.
